"""
TG-PY Admin Panel
Connects directly to Supabase — manage users, plans, licenses, devices.
Run: python admin_panel/main.py
"""
import sys
import os
import hashlib
import base64
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

# ── ENCRYPTED LICENSE SERVER CREDENTIALS ─────────────────────────────────────
# Set environment variables BEFORE license.db is imported

def _decrypt_config(encrypted: str) -> str:
    """Simple XOR decryption for config values."""
    key = 0x5A
    decoded = base64.b64decode(encrypted).decode('utf-8')
    return ''.join(chr(ord(c) ^ key) for c in decoded)

# Encrypted Supabase credentials (same as main.py) - GENERATED BY generate_encrypted.py
_ENCRYPTED_DB_HOST = "Oy0pd2t3Oyp3NDUoLjI/Oykud2t0KjU1Nj8odCkvKjs4Oyk/dDk1Nw=="
_ENCRYPTED_DB_USER = "KjUpLj0oPyl0PC4pNDk2Nz0zKz03NDAsNS8sMz0="
_ENCRYPTED_DB_PASS = "Dig7Pj82Myw/Ymxoa21taA=="

# Set environment variables BEFORE any license module imports
os.environ['TGPY_DB_HOST'] = _decrypt_config(_ENCRYPTED_DB_HOST)
os.environ['TGPY_DB_USER'] = _decrypt_config(_ENCRYPTED_DB_USER)
os.environ['TGPY_DB_PASS'] = _decrypt_config(_ENCRYPTED_DB_PASS)
os.environ['TGPY_DB_PORT'] = "5432"
os.environ['TGPY_DB_NAME'] = "postgres"

from PyQt6.QtWidgets import (
    QApplication, QMainWindow, QWidget, QVBoxLayout, QHBoxLayout,
    QTabWidget, QTableWidget, QTableWidgetItem, QHeaderView,
    QPushButton, QLabel, QLineEdit, QDialog, QFormLayout,
    QComboBox, QSpinBox, QMessageBox, QFrame,
    QTextEdit, QCheckBox, QAbstractItemView, QGroupBox,
)
from PyQt6.QtCore import Qt, QTimer
from PyQt6.QtGui import QColor, QFont

# ── Colors ────────────────────────────────────────────────────────────────────
C = {
    'bg':     '#0D1117', 'card':  '#161B22', 'border': '#30363D',
    'hover':  '#21262D', 'text':  '#F0F6FC', 'muted':  '#8B949E',
    'blue':   '#58A6FF', 'green': '#3FB950', 'red':    '#F85149',
    'yellow': '#D29922', 'purple':'#A371F7',
    'gblu': 'qlineargradient(x1:0,y1:0,x2:1,y2:1,stop:0 #58A6FF,stop:1 #1F6FEB)',
    'ggrn': 'qlineargradient(x1:0,y1:0,x2:1,y2:1,stop:0 #3FB950,stop:1 #238636)',
    'gred': 'qlineargradient(x1:0,y1:0,x2:1,y2:1,stop:0 #F85149,stop:1 #DA3633)',
    'gyel': 'qlineargradient(x1:0,y1:0,x2:1,y2:1,stop:0 #D29922,stop:1 #9E6A03)',
}

SS = f"""
QMainWindow,QWidget{{
    background:{C['bg']};color:{C['text']};
    font-family:'Segoe UI';font-size:13px;
}}
QTabWidget::pane{{
    background:{C['card']};border:1px solid {C['border']};
    border-radius:8px;margin-top:-1px;
}}
QTabBar::tab{{
    background:{C['hover']};border:1px solid {C['border']};
    padding:9px 22px;color:{C['muted']};
    border-radius:6px 6px 0 0;margin-right:3px;
}}
QTabBar::tab:selected{{
    background:{C['card']};color:{C['blue']};
    border-bottom:2px solid {C['blue']};font-weight:600;
}}
QTabBar::tab:hover:!selected{{color:{C['text']};}}
QTableWidget{{
    background:{C['card']};border:1px solid {C['border']};
    border-radius:8px;gridline-color:{C['border']};
    outline:0;
}}
QTableWidget::item{{
    padding:6px 10px;border:none;
    background:transparent;
}}
QTableWidget::item:selected{{
    background:rgba(88,166,255,0.15);
    color:{C['text']};border:none;
}}
QTableWidget::item:focus{{border:none;outline:0;background:transparent;}}
QHeaderView::section{{
    background:{C['hover']};border:none;
    border-right:1px solid {C['border']};
    border-bottom:1px solid {C['border']};
    padding:10px 10px;font-weight:600;
    color:{C['muted']};font-size:12px;
}}
QHeaderView::section:last{{border-right:none;}}
QScrollBar:vertical{{background:{C['bg']};width:8px;border-radius:4px;}}
QScrollBar::handle:vertical{{background:{C['border']};border-radius:4px;min-height:20px;}}
QScrollBar::handle:vertical:hover{{background:{C['muted']};}}
QScrollBar::add-line:vertical,QScrollBar::sub-line:vertical{{height:0px;}}
QScrollBar:horizontal{{background:{C['bg']};height:8px;border-radius:4px;}}
QScrollBar::handle:horizontal{{background:{C['border']};border-radius:4px;min-width:20px;}}
QScrollBar::handle:horizontal:hover{{background:{C['muted']};}}
QScrollBar::add-line:horizontal,QScrollBar::sub-line:horizontal{{width:0px;}}
QLineEdit,QComboBox,QSpinBox,QTextEdit{{
    background:{C['bg']};border:1.5px solid {C['border']};
    border-radius:8px;padding:8px 12px;color:{C['text']};
}}
QLineEdit:focus,QComboBox:focus,QSpinBox:focus{{border-color:{C['blue']};}}
QComboBox::drop-down{{border:none;padding-right:10px;}}
QComboBox QAbstractItemView{{
    background:{C['card']};border:1px solid {C['border']};
    color:{C['text']};selection-background-color:rgba(88,166,255,0.2);
}}
QPushButton{{
    background:{C['hover']};border:1px solid {C['border']};
    border-radius:8px;padding:8px 16px;color:{C['text']};
}}
QPushButton:hover{{background:#2D333B;border-color:{C['blue']};color:{C['blue']};}}
QDialog{{background:{C['bg']};border:1px solid {C['border']};}}
QLabel{{color:{C['text']};}}
QCheckBox{{spacing:8px;color:{C['text']};}}
QCheckBox::indicator{{width:16px;height:16px;border:1.5px solid {C['border']};border-radius:4px;background:{C['bg']};}}
QCheckBox::indicator:checked{{background:{C['blue']};border-color:{C['blue']};}}
QGroupBox{{
    border:1px solid {C['border']};border-radius:8px;
    margin-top:14px;padding:14px 12px 12px 12px;
    color:{C['muted']};font-weight:600;font-size:12px;
}}
QGroupBox::title{{subcontrol-origin:margin;left:12px;padding:0 6px;color:{C['blue']};}}
QGroupBox#checkable::indicator{{width:16px;height:16px;}}
QMessageBox{{background:{C['card']};color:{C['text']};}}
"""

# ── Helper: action button ─────────────────────────────────────────────────────
def _btn(text, grad, slot, w=None):
    b = QPushButton(text)
    b.setFixedHeight(32)
    if w: b.setFixedWidth(w)
    b.setStyleSheet(f"""
        QPushButton{{background:{grad};border:none;border-radius:7px;
                     color:white;font-weight:600;font-size:11px;padding:0 8px;}}
        QPushButton:hover{{opacity:0.85;}}
    """)
    b.setCursor(Qt.CursorShape.PointingHandCursor)
    b.clicked.connect(slot)
    return b

# ── Password helper ───────────────────────────────────────────────────────────
def _make_hash(pw: str) -> str:
    import bcrypt as _bc
    pre = hashlib.sha256(pw.encode()).hexdigest().encode()
    return _bc.hashpw(pre, _bc.gensalt(rounds=12)).decode()

def _verify_hash(pw: str, hsh: str) -> bool:
    import bcrypt as _bc
    pre = hashlib.sha256(pw.encode()).hexdigest().encode()
    return _bc.checkpw(pre, hsh.encode())

# ── Load plans from DB ────────────────────────────────────────────────────────
def _load_plans() -> list[dict]:
    """Returns list of plan dicts from tgpy_plans."""
    try:
        from license.db import db_cursor
        with db_cursor() as cur:
            cur.execute("SELECT id,name,duration_days,max_devices,description FROM tgpy_plans ORDER BY id")
            rows = cur.fetchall()
        return [{"id":r[0],"name":r[1],"duration_days":r[2],"max_devices":r[3],"description":r[4] or ""}
                for r in rows if r[1]]  # skip rows with NULL name
    except Exception:
        return []


# ══════════════════════════════════════════════════════════════════════════════
# PLANS TAB
# ══════════════════════════════════════════════════════════════════════════════
class PlansTab(QWidget):
    def __init__(self):
        super().__init__()
        self._build()
        self.load()

    def _build(self):
        lay = QVBoxLayout(self)
        lay.setSpacing(12)

        hdr = QHBoxLayout()
        lbl = QLabel("📋  Plans")
        lbl.setStyleSheet("font-size:16px;font-weight:bold;")
        hdr.addWidget(lbl)
        hdr.addStretch()
        hdr.addWidget(_btn("+ New Plan",  C['ggrn'], self._create, w=110))
        hdr.addWidget(_btn("🔄 Refresh", C['hover'], self.load,   w=100))
        lay.addLayout(hdr)

        # Info banner
        info = QLabel("Plans define what options are available when assigning a license to a user.")
        info.setStyleSheet(f"color:{C['muted']};font-size:12px;padding:8px 12px;"
                           f"background:{C['hover']};border-radius:6px;border:1px solid {C['border']};")
        lay.addWidget(info)

        self.table = QTableWidget()
        self.table.setColumnCount(6)
        self.table.setHorizontalHeaderLabels(
            ["Plan Name","Duration","Max Devices","Description","",""])
        hh = self.table.horizontalHeader()
        widths = [140, 100, 110, 0, 80, 80]
        modes  = [QHeaderView.ResizeMode.Fixed]*3 + [QHeaderView.ResizeMode.Stretch] + [QHeaderView.ResizeMode.Fixed]*2
        for i,(m,w) in enumerate(zip(modes,widths)):
            hh.setSectionResizeMode(i, m)
            if w: self.table.setColumnWidth(i, w)
        self.table.verticalHeader().setVisible(False)
        self.table.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.table.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.table.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.table.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.table.setAlternatingRowColors(False)
        lay.addWidget(self.table)

    def load(self):
        plans = _load_plans()
        self.table.setRowCount(len(plans))
        for r, p in enumerate(plans):
            dur = "♾ Lifetime" if p['duration_days'] == 0 else f"{p['duration_days']} days"
            self.table.setItem(r, 0, QTableWidgetItem(p['name']))
            self.table.setItem(r, 1, QTableWidgetItem(dur))
            self.table.setItem(r, 2, QTableWidgetItem(str(p['max_devices'])))
            self.table.setItem(r, 3, QTableWidgetItem(p['description']))

            ew = QWidget(); ew.setStyleSheet("background:transparent;")
            el = QHBoxLayout(ew); el.setContentsMargins(4,3,4,3)
            el.addWidget(_btn("✏ Edit", C['gblu'],
                lambda _, pid=p['id']: self._edit(pid), w=70))
            self.table.setCellWidget(r, 4, ew)

            dw = QWidget(); dw.setStyleSheet("background:transparent;")
            dl = QHBoxLayout(dw); dl.setContentsMargins(4,3,4,3)
            dl.addWidget(_btn("✕ Del", C['gred'],
                lambda _, pid=p['id'], pn=p['name']: self._delete(pid,pn), w=70))
            self.table.setCellWidget(r, 5, dw)
            self.table.setRowHeight(r, 44)

    def _create(self):
        dlg = PlanDialog(parent=self)
        if dlg.exec() == QDialog.DialogCode.Accepted:
            self.load()

    def _edit(self, plan_id: int):
        dlg = PlanDialog(plan_id=plan_id, parent=self)
        if dlg.exec() == QDialog.DialogCode.Accepted:
            self.load()

    def _delete(self, plan_id: int, name: str):
        r = QMessageBox.question(self, "Delete Plan",
            f"Delete plan '{name}'?\nExisting licenses using this plan will NOT be affected.",
            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No)
        if r == QMessageBox.StandardButton.Yes:
            try:
                from license.db import db_cursor
                with db_cursor() as cur:
                    cur.execute("DELETE FROM tgpy_plans WHERE id=%s", (plan_id,))
                self.load()
            except Exception as e:
                QMessageBox.critical(self, "Error", str(e))


# ══════════════════════════════════════════════════════════════════════════════
# USERS TAB
# ══════════════════════════════════════════════════════════════════════════════
class UsersTab(QWidget):
    def __init__(self):
        super().__init__()
        self._build()
        self.load()

    def _build(self):
        lay = QVBoxLayout(self)
        lay.setSpacing(12)
        hdr = QHBoxLayout()
        lbl = QLabel("👤  Users")
        lbl.setStyleSheet("font-size:16px;font-weight:bold;")
        hdr.addWidget(lbl)
        hdr.addStretch()
        hdr.addWidget(_btn("+ New User", C['ggrn'], self._create, w=120))
        hdr.addWidget(_btn("🔄 Refresh", C['hover'], self.load,   w=100))
        lay.addLayout(hdr)

        self.table = QTableWidget()
        self.table.setColumnCount(7)
        self.table.setHorizontalHeaderLabels(
            ["Username","Full Name","Email","Plan","Active","Created","Actions"])
        hh = self.table.horizontalHeader()
        for i,(m,w) in enumerate([
            (QHeaderView.ResizeMode.Fixed,120),
            (QHeaderView.ResizeMode.Stretch,0),
            (QHeaderView.ResizeMode.Stretch,0),
            (QHeaderView.ResizeMode.Fixed,90),
            (QHeaderView.ResizeMode.Fixed,55),
            (QHeaderView.ResizeMode.Fixed,110),
            (QHeaderView.ResizeMode.Fixed,200),
        ]):
            hh.setSectionResizeMode(i, m)
            if w: self.table.setColumnWidth(i, w)
        self.table.verticalHeader().setVisible(False)
        self.table.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.table.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.table.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.table.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.table.setAlternatingRowColors(False)
        lay.addWidget(self.table)

    def load(self):
        try:
            from license.db import db_cursor
            from datetime import datetime, timezone
            with db_cursor() as cur:
                cur.execute("""
                    SELECT u.id, u.username, u.full_name, u.email,
                           u.is_active, u.created_at,
                           (SELECT l.plan_name FROM tgpy_licenses l
                            WHERE l.user_id=u.id AND l.is_active=TRUE
                            ORDER BY l.created_at DESC LIMIT 1) AS plan,
                           (SELECT CASE
                                WHEN l.expires_at IS NULL THEN 'lifetime'
                                WHEN l.expires_at > NOW() THEN 'active'
                                ELSE 'expired' END
                            FROM tgpy_licenses l
                            WHERE l.user_id=u.id AND l.is_active=TRUE
                            ORDER BY l.created_at DESC LIMIT 1) AS lic_status
                    FROM tgpy_users u
                    ORDER BY u.created_at DESC
                """)
                rows = cur.fetchall()
            self.table.setRowCount(len(rows))
            for r, row in enumerate(rows):
                uid,uname,fname,email,active,created,plan,lic_status = row

                self.table.setItem(r,0,QTableWidgetItem(uname))
                self.table.setItem(r,1,QTableWidgetItem(fname or ""))
                self.table.setItem(r,2,QTableWidgetItem(email or ""))

                plan_lbl = plan or "—"
                plan_item = QTableWidgetItem(plan_lbl)
                if lic_status == 'active':
                    plan_item.setForeground(QColor(C['green']))
                elif lic_status == 'expired':
                    plan_item.setForeground(QColor(C['red']))
                elif lic_status == 'lifetime':
                    plan_item.setForeground(QColor(C['purple']))
                else:
                    plan_item.setForeground(QColor(C['muted']))
                self.table.setItem(r,3,plan_item)

                si = QTableWidgetItem("✓" if active else "✕")
                si.setForeground(QColor(C['green'] if active else C['red']))
                self.table.setItem(r,4,si)

                dt = created.strftime("%Y-%m-%d") if created else ""
                self.table.setItem(r,5,QTableWidgetItem(dt))

                aw = QWidget(); aw.setStyleSheet("background:transparent;")
                al = QHBoxLayout(aw); al.setContentsMargins(4,3,4,3); al.setSpacing(4)
                al.addWidget(_btn("🔑 License", C['gblu'],
                    lambda _, u=str(uid),n=uname: self._add_lic(u,n), w=85))
                al.addWidget(_btn("✏", C['hover'],
                    lambda _, u=str(uid): self._edit(u), w=30))
                al.addWidget(_btn("✕", C['gred'],
                    lambda _, u=str(uid),n=uname: self._del(u,n), w=30))
                self.table.setCellWidget(r,6,aw)
                self.table.setRowHeight(r,44)
        except Exception as e:
            QMessageBox.critical(self,"DB Error",str(e))

    def _create(self):
        dlg = UserDialog(parent=self)
        if dlg.exec() == QDialog.DialogCode.Accepted:
            self.load()

    def _edit(self, uid):
        dlg = UserDialog(user_id=uid, parent=self)
        if dlg.exec() == QDialog.DialogCode.Accepted:
            self.load()

    def _add_lic(self, uid, uname):
        dlg = LicenseDialog(user_id=uid, username=uname, parent=self)
        if dlg.exec() == QDialog.DialogCode.Accepted:
            self.load()

    def _del(self, uid, uname):
        r = QMessageBox.question(self,"Delete User",
            f"Delete '{uname}'?\nAll licenses and devices will be removed.",
            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No)
        if r == QMessageBox.StandardButton.Yes:
            try:
                from license.db import db_cursor
                with db_cursor() as cur:
                    cur.execute("DELETE FROM tgpy_users WHERE id=%s",(uid,))
                self.load()
            except Exception as e:
                QMessageBox.critical(self,"Error",str(e))


# ══════════════════════════════════════════════════════════════════════════════
# LICENSES TAB
# ══════════════════════════════════════════════════════════════════════════════
class LicensesTab(QWidget):
    def __init__(self):
        super().__init__()
        self._build()
        self.load()

    def _build(self):
        lay = QVBoxLayout(self)
        lay.setSpacing(12)
        hdr = QHBoxLayout()
        lbl = QLabel("🔑  Licenses")
        lbl.setStyleSheet("font-size:16px;font-weight:bold;")
        hdr.addWidget(lbl)
        hdr.addStretch()
        hdr.addWidget(_btn("🔄 Refresh", C['hover'], self.load, w=100))
        lay.addLayout(hdr)

        self.table = QTableWidget()
        self.table.setColumnCount(8)
        self.table.setHorizontalHeaderLabels(
            ["User","Plan","Devices","Starts","Expires","Status","Days Left","Actions"])
        hh = self.table.horizontalHeader()
        for i,(m,w) in enumerate([
            (QHeaderView.ResizeMode.Fixed,110),
            (QHeaderView.ResizeMode.Fixed,80),
            (QHeaderView.ResizeMode.Fixed,65),
            (QHeaderView.ResizeMode.Fixed,100),
            (QHeaderView.ResizeMode.Fixed,100),
            (QHeaderView.ResizeMode.Fixed,80),
            (QHeaderView.ResizeMode.Fixed,80),
            (QHeaderView.ResizeMode.Fixed,155),
        ]):
            hh.setSectionResizeMode(i, m)
            if w: self.table.setColumnWidth(i, w)
        self.table.verticalHeader().setVisible(False)
        self.table.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.table.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.table.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.table.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.table.setAlternatingRowColors(False)
        lay.addWidget(self.table)

    def load(self):
        try:
            from license.db import db_cursor
            from datetime import datetime, timezone
            with db_cursor() as cur:
                cur.execute("""
                    SELECT l.id,u.username,l.plan_name,l.max_devices,
                           l.starts_at,l.expires_at,l.is_active,
                           (SELECT COUNT(*) FROM tgpy_devices d
                            WHERE d.license_id=l.id AND d.is_active=TRUE) AS dc
                    FROM tgpy_licenses l
                    JOIN tgpy_users u ON u.id=l.user_id
                    ORDER BY l.created_at DESC
                """)
                rows = cur.fetchall()
            self.table.setRowCount(len(rows))
            now = datetime.now(timezone.utc)
            for r,row in enumerate(rows):
                lid,uname,plan,mdev,starts,expires,active,dc = row
                self.table.setItem(r,0,QTableWidgetItem(uname))
                self.table.setItem(r,1,QTableWidgetItem(plan))
                self.table.setItem(r,2,QTableWidgetItem(f"{dc}/{mdev}"))
                self.table.setItem(r,3,QTableWidgetItem(
                    starts.strftime("%Y-%m-%d") if starts else ""))
                self.table.setItem(r,4,QTableWidgetItem(
                    expires.strftime("%Y-%m-%d") if expires else "♾ Lifetime"))

                if not active:
                    st,col,days = "Inactive",C['muted'],"—"
                elif expires is None:
                    st,col,days = "Active",C['green'],"♾"
                elif expires.replace(tzinfo=timezone.utc) > now:
                    d=(expires.replace(tzinfo=timezone.utc)-now).days
                    st="Active"; col=C['green'] if d>7 else C['yellow']; days=str(d)
                else:
                    st,col,days="Expired",C['red'],"0"

                si=QTableWidgetItem(st); si.setForeground(QColor(col))
                self.table.setItem(r,5,si)
                self.table.setItem(r,6,QTableWidgetItem(days))

                aw=QWidget(); aw.setStyleSheet("background:transparent;")
                al=QHBoxLayout(aw); al.setContentsMargins(4,3,4,3); al.setSpacing(4)
                al.addWidget(_btn("⟳ Extend", "#1F6FEB",
                    lambda _,l=str(lid): self._extend(l), w=80))
                al.addWidget(_btn("⊘ Revoke" if active else "✓ Enable",
                    C['gred'] if active else C['ggrn'],
                    lambda _,l=str(lid),a=active: self._toggle(l,a), w=80))
                self.table.setCellWidget(r,7,aw)
                self.table.setRowHeight(r,44)
        except Exception as e:
            QMessageBox.critical(self,"DB Error",str(e))

    def _extend(self, lid):
        from PyQt6.QtWidgets import QInputDialog
        val,ok = QInputDialog.getInt(self,"Extend","Days to add:",30,1,3650)
        if not ok: return
        try:
            from license.db import db_cursor
            with db_cursor() as cur:
                cur.execute("""
                    UPDATE tgpy_licenses
                    SET expires_at=GREATEST(COALESCE(expires_at,NOW()),NOW())
                                   +(%s||' days')::INTERVAL, is_active=TRUE
                    WHERE id=%s""", (str(val),lid))
            self.load()
        except Exception as e:
            QMessageBox.critical(self,"Error",str(e))

    def _toggle(self, lid, active):
        try:
            from license.db import db_cursor
            with db_cursor() as cur:
                cur.execute("UPDATE tgpy_licenses SET is_active=%s WHERE id=%s",
                            (not active, lid))
            self.load()
        except Exception as e:
            QMessageBox.critical(self,"Error",str(e))


# ══════════════════════════════════════════════════════════════════════════════
# DEVICES TAB
# ══════════════════════════════════════════════════════════════════════════════
class DevicesTab(QWidget):
    def __init__(self):
        super().__init__()
        self._build()
        self.load()

    def _build(self):
        lay = QVBoxLayout(self)
        lay.setSpacing(12)
        hdr = QHBoxLayout()
        lbl = QLabel("💻  Devices")
        lbl.setStyleSheet("font-size:16px;font-weight:bold;")
        hdr.addWidget(lbl)
        hdr.addStretch()
        hdr.addWidget(_btn("🔄 Refresh", C['hover'], self.load, w=100))
        lay.addLayout(hdr)
        self.table = QTableWidget()
        self.table.setColumnCount(7)
        self.table.setHorizontalHeaderLabels(
            ["User","Hostname","Platform","Hardware ID","Activated","Last Seen","Action"])
        hh = self.table.horizontalHeader()
        for i,(m,w) in enumerate([
            (QHeaderView.ResizeMode.Fixed,100),
            (QHeaderView.ResizeMode.Fixed,130),
            (QHeaderView.ResizeMode.Fixed,150),
            (QHeaderView.ResizeMode.Stretch,0),
            (QHeaderView.ResizeMode.Fixed,110),
            (QHeaderView.ResizeMode.Fixed,130),
            (QHeaderView.ResizeMode.Fixed,90),
        ]):
            hh.setSectionResizeMode(i, m)
            if w: self.table.setColumnWidth(i, w)
        self.table.verticalHeader().setVisible(False)
        self.table.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.table.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.table.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.table.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.table.setAlternatingRowColors(False)
        lay.addWidget(self.table)

    def load(self):
        try:
            from license.db import db_cursor
            with db_cursor() as cur:
                cur.execute("""
                    SELECT d.id,u.username,d.hostname,d.platform,
                           d.hardware_id,d.activated_at,d.last_seen
                    FROM tgpy_devices d
                    JOIN tgpy_licenses l ON l.id=d.license_id
                    JOIN tgpy_users u ON u.id=l.user_id
                    ORDER BY d.last_seen DESC
                """)
                rows = cur.fetchall()
            self.table.setRowCount(len(rows))
            for r,row in enumerate(rows):
                did,uname,host,plat,hwid,act,last = row
                self.table.setItem(r,0,QTableWidgetItem(uname))
                self.table.setItem(r,1,QTableWidgetItem(host or ""))
                self.table.setItem(r,2,QTableWidgetItem(plat or ""))
                self.table.setItem(r,3,QTableWidgetItem((hwid or "")[:20]+"…"))
                self.table.setItem(r,4,QTableWidgetItem(
                    act.strftime("%Y-%m-%d") if act else ""))
                self.table.setItem(r,5,QTableWidgetItem(
                    last.strftime("%Y-%m-%d %H:%M") if last else ""))
                aw=QWidget(); aw.setStyleSheet("background:transparent;")
                al=QHBoxLayout(aw); al.setContentsMargins(4,3,4,3)
                al.addWidget(_btn("✕ Remove", C['gred'],
                    lambda _,d=str(did): self._remove(d), w=90))
                self.table.setCellWidget(r,6,aw)
                self.table.setRowHeight(r,40)
        except Exception as e:
            QMessageBox.critical(self,"DB Error",str(e))

    def _remove(self, did):
        r=QMessageBox.question(self,"Remove Device",
            "Remove this device?\nUser will need to re-activate.",
            QMessageBox.StandardButton.Yes|QMessageBox.StandardButton.No)
        if r==QMessageBox.StandardButton.Yes:
            try:
                from license.db import db_cursor
                with db_cursor() as cur:
                    cur.execute("DELETE FROM tgpy_devices WHERE id=%s",(did,))
                self.load()
            except Exception as e:
                QMessageBox.critical(self,"Error",str(e))


# ══════════════════════════════════════════════════════════════════════════════
# DIALOGS
# ══════════════════════════════════════════════════════════════════════════════

class PlanDialog(QDialog):
    """Create / Edit a plan."""
    def __init__(self, plan_id=None, parent=None):
        super().__init__(parent)
        self.plan_id = plan_id
        self.setWindowTitle("Edit Plan" if plan_id else "New Plan")
        self.setMinimumWidth(400)
        self._build()
        if plan_id:
            self._load()

    def _build(self):
        lay = QVBoxLayout(self)
        lay.setSpacing(14); lay.setContentsMargins(28,28,28,28)

        title = QLabel("📋 " + ("Edit Plan" if self.plan_id else "Create New Plan"))
        title.setStyleSheet("font-size:16px;font-weight:bold;")
        lay.addWidget(title)

        form = QFormLayout(); form.setSpacing(10)
        self.name_in  = QLineEdit()
        self.name_in.setPlaceholderText("e.g. basic, pro, enterprise")
        self.dur_spin = QSpinBox()
        self.dur_spin.setRange(0, 3650)
        self.dur_spin.setValue(30)
        self.dur_spin.setSuffix(" days  (0 = Lifetime)")
        self.dev_spin = QSpinBox()
        self.dev_spin.setRange(1, 20)
        self.dev_spin.setValue(1)
        self.desc_in  = QLineEdit()
        self.desc_in.setPlaceholderText("Optional description")

        form.addRow("Plan Name *",   self.name_in)
        form.addRow("Duration",      self.dur_spin)
        form.addRow("Max Devices",   self.dev_spin)
        form.addRow("Description",   self.desc_in)
        lay.addLayout(form)

        # Quick presets
        grp = QGroupBox("Quick Presets")
        gl  = QHBoxLayout(grp); gl.setSpacing(8)
        for label, dur, dev in [
            ("Trial (7d / 1 dev)",  7, 1),
            ("Basic (30d / 1 dev)", 30, 1),
            ("Pro (30d / 3 dev)",   30, 3),
            ("Lifetime",             0, 2),
        ]:
            b = QPushButton(label)
            b.setFixedHeight(28)
            b.setStyleSheet(f"QPushButton{{background:{C['hover']};border:1px solid {C['border']};"
                            f"border-radius:6px;color:{C['text']};font-size:11px;}}"
                f"QPushButton:hover{{border-color:{C['blue']};color:{C['blue']}}}")
            b.clicked.connect(lambda _,d=dur,dv=dev: (
                self.dur_spin.setValue(d), self.dev_spin.setValue(dv)))
            gl.addWidget(b)
        lay.addWidget(grp)

        btns = QHBoxLayout(); btns.addStretch()
        can = QPushButton("Cancel"); can.clicked.connect(self.reject)
        sav = QPushButton("💾 Save Plan")
        sav.setStyleSheet(f"QPushButton{{background:{C['ggrn']};border:none;"
                          f"border-radius:8px;color:white;font-weight:600;padding:8px 20px;}}")
        sav.clicked.connect(self._save)
        btns.addWidget(can); btns.addWidget(sav)
        lay.addLayout(btns)

    def _load(self):
        from license.db import db_cursor
        with db_cursor() as cur:
            cur.execute("SELECT name,duration_days,max_devices,description FROM tgpy_plans WHERE id=%s",
                        (self.plan_id,))
            row = cur.fetchone()
        if row:
            self.name_in.setText(row[0])
            self.dur_spin.setValue(row[1])
            self.dev_spin.setValue(row[2])
            self.desc_in.setText(row[3] or "")

    def _save(self):
        name = self.name_in.text().strip()
        if not name:
            QMessageBox.warning(self,"Error","Plan name is required."); return
        try:
            from license.db import db_cursor
            with db_cursor() as cur:
                if self.plan_id:
                    cur.execute("""UPDATE tgpy_plans SET name=%s,duration_days=%s,
                        max_devices=%s,description=%s WHERE id=%s""",
                        (name,self.dur_spin.value(),self.dev_spin.value(),
                         self.desc_in.text(),self.plan_id))
                else:
                    cur.execute("""INSERT INTO tgpy_plans(name,duration_days,max_devices,description)
                        VALUES(%s,%s,%s,%s)""",
                        (name,self.dur_spin.value(),self.dev_spin.value(),self.desc_in.text()))
            self.accept()
        except Exception as e:
            QMessageBox.critical(self,"Error",str(e))


class UserDialog(QDialog):
    """Create / Edit user — with optional instant license assignment."""
    def __init__(self, user_id=None, parent=None):
        super().__init__(parent)
        self.user_id = user_id
        self.setWindowTitle("Edit User" if user_id else "New User")
        self.setMinimumWidth(460)
        self._build()
        if user_id:
            self._load()

    def _build(self):
        lay = QVBoxLayout(self)
        lay.setSpacing(14); lay.setContentsMargins(28,28,28,28)

        title = QLabel("👤 " + ("Edit User" if self.user_id else "Create New User"))
        title.setStyleSheet("font-size:16px;font-weight:bold;")
        lay.addWidget(title)

        # ── User details ──────────────────────────────────────────────────────
        user_grp = QGroupBox("User Details")
        uf = QFormLayout(user_grp); uf.setSpacing(10)
        self.uname_in = QLineEdit()
        self.fname_in = QLineEdit()
        self.email_in = QLineEdit()
        self.pass_in  = QLineEdit()
        self.pass_in.setEchoMode(QLineEdit.EchoMode.Password)
        self.pass_in.setPlaceholderText(
            "Leave blank to keep current" if self.user_id else "Required")
        self.active_cb = QCheckBox("Active")
        self.active_cb.setChecked(True)
        uf.addRow("Username *",  self.uname_in)
        uf.addRow("Full Name",   self.fname_in)
        uf.addRow("Email",       self.email_in)
        uf.addRow("Password",    self.pass_in)
        uf.addRow("",            self.active_cb)
        lay.addWidget(user_grp)

        # ── License assignment (only for new user) ────────────────────────────
        if not self.user_id:
            self.lic_grp = QGroupBox("Assign License (optional)")
            self.lic_grp.setCheckable(True)
            self.lic_grp.setChecked(False)
            lf = QFormLayout(self.lic_grp); lf.setSpacing(10)

            self.plan_combo = QComboBox()
            self._populate_plans()
            self.plan_combo.currentIndexChanged.connect(self._on_plan_changed)

            self.dur_spin = QSpinBox()
            self.dur_spin.setRange(1, 3650)
            self.dur_spin.setValue(30)
            self.dur_spin.setSuffix(" days")

            self.lifetime_cb = QCheckBox("Lifetime (no expiry)")
            self.lifetime_cb.toggled.connect(
                lambda c: self.dur_spin.setEnabled(not c))

            self.dev_spin = QSpinBox()
            self.dev_spin.setRange(1, 10)
            self.dev_spin.setValue(1)

            self.lic_notes = QLineEdit()
            self.lic_notes.setPlaceholderText("Optional notes")

            lf.addRow("Plan",        self.plan_combo)
            lf.addRow("Duration",    self.dur_spin)
            lf.addRow("",            self.lifetime_cb)
            lf.addRow("Max Devices", self.dev_spin)
            lf.addRow("Notes",       self.lic_notes)
            lay.addWidget(self.lic_grp)

        # ── Buttons ───────────────────────────────────────────────────────────
        btns = QHBoxLayout(); btns.addStretch()
        can = QPushButton("Cancel"); can.clicked.connect(self.reject)
        sav = QPushButton("💾 Save")
        sav.setStyleSheet(f"QPushButton{{background:{C['ggrn']};border:none;"
                          f"border-radius:8px;color:white;font-weight:600;padding:8px 24px;}}")
        sav.clicked.connect(self._save)
        btns.addWidget(can); btns.addWidget(sav)
        lay.addLayout(btns)

    def _populate_plans(self):
        self.plan_combo.clear()
        self._plans = _load_plans()
        for p in self._plans:
            dur = "Lifetime" if p['duration_days'] == 0 else f"{p['duration_days']}d"
            self.plan_combo.addItem(
                f"{p['name']}  ({dur} / {p['max_devices']} device(s))",
                userData=p)
        # blank option at top
        self.plan_combo.insertItem(0, "— Select Plan —", userData=None)
        self.plan_combo.setCurrentIndex(0)

    def _on_plan_changed(self, idx):
        plan = self.plan_combo.currentData()
        if not plan: return
        if plan['duration_days'] == 0:
            self.lifetime_cb.setChecked(True)
        else:
            self.lifetime_cb.setChecked(False)
            self.dur_spin.setValue(plan['duration_days'])
        self.dev_spin.setValue(plan['max_devices'])

    def _load(self):
        from license.db import db_cursor
        with db_cursor() as cur:
            cur.execute(
                "SELECT username,full_name,email,is_active FROM tgpy_users WHERE id=%s",
                (self.user_id,))
            row = cur.fetchone()
        if row:
            self.uname_in.setText(row[0])
            self.fname_in.setText(row[1] or "")
            self.email_in.setText(row[2] or "")
            self.active_cb.setChecked(row[3])

    def _save(self):
        uname = self.uname_in.text().strip()
        pw    = self.pass_in.text().strip()
        if not uname:
            QMessageBox.warning(self,"Error","Username is required."); return
        if not self.user_id and not pw:
            QMessageBox.warning(self,"Error","Password is required for new user."); return
        try:
            from license.db import db_cursor
            with db_cursor() as cur:
                if self.user_id:
                    if pw:
                        cur.execute("""UPDATE tgpy_users
                            SET username=%s,full_name=%s,email=%s,
                                password_hash=%s,is_active=%s WHERE id=%s""",
                            (uname,self.fname_in.text(),self.email_in.text(),
                             _make_hash(pw),self.active_cb.isChecked(),self.user_id))
                    else:
                        cur.execute("""UPDATE tgpy_users
                            SET username=%s,full_name=%s,email=%s,is_active=%s WHERE id=%s""",
                            (uname,self.fname_in.text(),self.email_in.text(),
                             self.active_cb.isChecked(),self.user_id))
                else:
                    # Create user
                    cur.execute("""INSERT INTO tgpy_users
                        (username,password_hash,full_name,email,is_active)
                        VALUES(%s,%s,%s,%s,%s) RETURNING id""",
                        (uname,_make_hash(pw),self.fname_in.text(),
                         self.email_in.text(),self.active_cb.isChecked()))
                    new_user_id = str(cur.fetchone()[0])

                    # Assign license if checked
                    if hasattr(self,'lic_grp') and self.lic_grp.isChecked():
                        plan = self.plan_combo.currentData()
                        plan_name = plan['name'] if plan else "basic"
                        lifetime  = self.lifetime_cb.isChecked()
                        dur       = self.dur_spin.value()
                        max_dev   = self.dev_spin.value()
                        notes     = self.lic_notes.text()
                        if lifetime:
                            cur.execute("""INSERT INTO tgpy_licenses
                                (user_id,plan_name,max_devices,notes)
                                VALUES(%s,%s,%s,%s)""",
                                (new_user_id,plan_name,max_dev,notes))
                        else:
                            cur.execute("""INSERT INTO tgpy_licenses
                                (user_id,plan_name,max_devices,
                                 starts_at,expires_at,notes)
                                VALUES(%s,%s,%s,NOW(),
                                       NOW()+(%s||' days')::INTERVAL,%s)""",
                                (new_user_id,plan_name,max_dev,str(dur),notes))

            self.accept()
        except Exception as e:
            QMessageBox.critical(self,"Error",str(e))


class LicenseDialog(QDialog):
    """Add license to existing user."""
    def __init__(self, user_id, username, parent=None):
        super().__init__(parent)
        self.user_id  = user_id
        self.username = username
        self.setWindowTitle(f"Create License — {username}")
        self.setMinimumWidth(420)
        self._build()

    def _build(self):
        lay = QVBoxLayout(self)
        lay.setSpacing(14); lay.setContentsMargins(28,28,28,28)

        title = QLabel(f"🔑 New License for  <b>{self.username}</b>")
        title.setStyleSheet("font-size:15px;")
        lay.addWidget(title)

        form = QFormLayout(); form.setSpacing(10)
        self.plan_combo = QComboBox()
        self._plans = _load_plans()
        for p in self._plans:
            dur = "Lifetime" if p['duration_days']==0 else f"{p['duration_days']}d"
            self.plan_combo.addItem(
                f"{p['name']}  ({dur} / {p['max_devices']} device(s))", userData=p)
        self.plan_combo.insertItem(0,"— Select Plan —",userData=None)
        self.plan_combo.setCurrentIndex(0)
        self.plan_combo.currentIndexChanged.connect(self._on_plan)

        self.dur_spin = QSpinBox()
        self.dur_spin.setRange(1,3650); self.dur_spin.setValue(30)
        self.dur_spin.setSuffix(" days")
        self.lifetime_cb = QCheckBox("Lifetime (no expiry)")
        self.lifetime_cb.toggled.connect(lambda c: self.dur_spin.setEnabled(not c))
        self.dev_spin = QSpinBox()
        self.dev_spin.setRange(1,10); self.dev_spin.setValue(1)
        self.notes_in = QLineEdit()
        self.notes_in.setPlaceholderText("Optional notes")

        form.addRow("Plan *",       self.plan_combo)
        form.addRow("Duration",     self.dur_spin)
        form.addRow("",             self.lifetime_cb)
        form.addRow("Max Devices",  self.dev_spin)
        form.addRow("Notes",        self.notes_in)
        lay.addLayout(form)

        btns = QHBoxLayout(); btns.addStretch()
        can = QPushButton("Cancel"); can.clicked.connect(self.reject)
        sav = QPushButton("🔑 Create License")
        sav.setStyleSheet(f"QPushButton{{background:{C['ggrn']};border:none;"
                          f"border-radius:8px;color:white;font-weight:600;padding:8px 20px;}}")
        sav.clicked.connect(self._save)
        btns.addWidget(can); btns.addWidget(sav)
        lay.addLayout(btns)

    def _on_plan(self, idx):
        plan = self.plan_combo.currentData()
        if not plan: return
        if plan['duration_days'] == 0:
            self.lifetime_cb.setChecked(True)
        else:
            self.lifetime_cb.setChecked(False)
            self.dur_spin.setValue(plan['duration_days'])
        self.dev_spin.setValue(plan['max_devices'])

    def _save(self):
        plan = self.plan_combo.currentData()
        if not plan:
            QMessageBox.warning(self,"Error","Please select a plan."); return
        try:
            from license.db import db_cursor
            lifetime = self.lifetime_cb.isChecked()
            dur = self.dur_spin.value()
            with db_cursor() as cur:
                if lifetime:
                    cur.execute("""INSERT INTO tgpy_licenses
                        (user_id,plan_name,max_devices,notes)
                        VALUES(%s,%s,%s,%s)""",
                        (self.user_id,plan['name'],self.dev_spin.value(),
                         self.notes_in.text()))
                else:
                    cur.execute("""INSERT INTO tgpy_licenses
                        (user_id,plan_name,max_devices,starts_at,expires_at,notes)
                        VALUES(%s,%s,%s,NOW(),NOW()+(%s||' days')::INTERVAL,%s)""",
                        (self.user_id,plan['name'],self.dev_spin.value(),
                         str(dur),self.notes_in.text()))
            QMessageBox.information(self,"Done",
                f"License created!\nPlan: {plan['name']}\n"
                f"Duration: {'Lifetime' if lifetime else f'{dur} days'}\n"
                f"Max Devices: {self.dev_spin.value()}")
            self.accept()
        except Exception as e:
            QMessageBox.critical(self,"Error",str(e))


# ══════════════════════════════════════════════════════════════════════════════
# MAIN WINDOW
# ══════════════════════════════════════════════════════════════════════════════
class AdminWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("TG-PY Admin Panel")
        self.setMinimumSize(1100, 720)
        self.resize(1250, 780)
        self.setStyleSheet(SS)
        self._build()

    def _build(self):
        cen = QWidget()
        self.setCentralWidget(cen)
        lay = QVBoxLayout(cen)
        lay.setContentsMargins(16,16,16,16); lay.setSpacing(12)

        # Header
        hdr = QHBoxLayout()
        t = QLabel("🔧  TG-PY Admin Panel")
        t.setStyleSheet("font-size:22px;font-weight:bold;")
        hdr.addWidget(t); hdr.addStretch()
        self.conn_lbl = QLabel("⚪ Connecting…")
        self.conn_lbl.setStyleSheet(f"color:{C['muted']};font-size:12px;")
        hdr.addWidget(self.conn_lbl)
        lay.addLayout(hdr)

        sep = QFrame()
        sep.setFrameShape(QFrame.Shape.HLine)
        sep.setStyleSheet(f"background:{C['border']};max-height:1px;")
        lay.addWidget(sep)

        self.tabs = QTabWidget()
        self.plans_tab    = PlansTab()
        self.users_tab    = UsersTab()
        self.licenses_tab = LicensesTab()
        self.devices_tab  = DevicesTab()
        self.tabs.addTab(self.plans_tab,    "📋  Plans")
        self.tabs.addTab(self.users_tab,    "👤  Users")
        self.tabs.addTab(self.licenses_tab, "🔑  Licenses")
        self.tabs.addTab(self.devices_tab,  "💻  Devices")
        lay.addWidget(self.tabs)

        QTimer.singleShot(500, self._check_conn)

    def _check_conn(self):
        try:
            from license.db import get_connection
            get_connection()
            self.conn_lbl.setText("🟢 Connected to Supabase")
            self.conn_lbl.setStyleSheet(f"color:{C['green']};font-size:12px;")
        except Exception as e:
            self.conn_lbl.setText(f"🔴 {str(e)[:60]}")
            self.conn_lbl.setStyleSheet(f"color:{C['red']};font-size:12px;")


def main():
    app = QApplication(sys.argv)
    app.setApplicationName("TG-PY Admin")
    app.setFont(QFont("Segoe UI", 10))
    w = AdminWindow()
    w.show()
    sys.exit(app.exec())


if __name__ == "__main__":
    main()